[profile.default]
src = "contracts/src"
out = "contracts/out"
test = "contracts/test"
script = "contracts/script"
libs = ["lib"]
cache_path = "contracts/cache"
broadcast = "contracts/broadcast"
via_ir = true
optimizer = true
optimizer_runs = 200

# Allow file operations for deployment scripts
fs_permissions = [
    { access = "read-write", path = "./" },
    { access = "read-write", path = "./deployments" },
    { access = "read-write", path = "./frontend" }
]

[profile.default.fuzz]
runs = 256

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
